# Generated by Django 3.2.7 on 2021-09-27 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_side', '0003_flag'),
    ]

    operations = [
        migrations.AddField(
            model_name='flag',
            name='box',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='admin_side.gamebox'),
        ),
    ]
