# Generated by Django 3.2.7 on 2021-09-29 13:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('admin_side', '0004_flag_box'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamebox',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='gamebox',
            name='ip',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='gamebox',
            name='ssh_password',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='gamebox',
            name='ssh_port',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='gamebox',
            name='ssh_user',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='gamebox',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
