# Generated by Django 3.2.7 on 2021-10-04 12:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_side', '0006_game_settings'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rounds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_dugaar', models.IntegerField(null=True)),
                ('flags', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='admin_side.flag')),
            ],
        ),
    ]
